server:
  port: 8080
spring:
  application:
    name: spring-demo-app
#  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://
    username: root
    password: 11111

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#实体类包名 可以再xml中省略返回对象的包路径
  type-aliases-package:
#    开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

