server:
  port: 8080
spring:
  application:
    name: spring-demo-app
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    url: jdbc:h2:mem:test #配置h2数据库的连接地址
    username: sa
    password: sa
  h2:
    console:
      enabled: true #开启web console功能

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #实体类包名 可以再xml中省略返回对象的包路径
  type-aliases-package:
  #    开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

fruit:
  name: apple
  type: hongfushi

# 配置值 优先于默认值
#basicAuth-userName: tom
#basicAuth-password: 11111
#
#security:
#  basic:
#    enabled: true
#    paths: /**

#  Diary
logging:
  level:
    root: warn  # 配置root级别日志级别 默认是info

    cn:
      felord: debug



